/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSyncsRouteImport } from './routes/_authenticated/syncs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlatformsRouteImport } from './routes/_authenticated/platforms'
import { Route as AuthenticatedFinancialRouteImport } from './routes/_authenticated/financial'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers.index'
import { Route as AuthenticatedProvidersIdRouteImport } from './routes/_authenticated/providers.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksUpdateUsdRateRouteImport } from './routes/api/public/hooks/update-usd-rate'
import { Route as ApiPublicCronSyncBillingRouteImport } from './routes/api/public/cron/sync-billing'
import { Route as ApiPublicCronSyncAllRouteImport } from './routes/api/public/cron/sync-all'
import { Route as ApiPublicCronEvaluateAlertsRouteImport } from './routes/api/public/cron/evaluate-alerts'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyncsRoute = AuthenticatedSyncsRouteImport.update({
  id: '/syncs',
  path: '/syncs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformsRoute = AuthenticatedPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialRoute = AuthenticatedFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvidersIdRoute =
  AuthenticatedProvidersIdRouteImport.update({
    id: '/providers/$id',
    path: '/providers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUpdateUsdRateRoute =
  ApiPublicHooksUpdateUsdRateRouteImport.update({
    id: '/api/public/hooks/update-usd-rate',
    path: '/api/public/hooks/update-usd-rate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncBillingRoute =
  ApiPublicCronSyncBillingRouteImport.update({
    id: '/api/public/cron/sync-billing',
    path: '/api/public/cron/sync-billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncAllRoute = ApiPublicCronSyncAllRouteImport.update({
  id: '/api/public/cron/sync-all',
  path: '/api/public/cron/sync-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronEvaluateAlertsRoute =
  ApiPublicCronEvaluateAlertsRouteImport.update({
    id: '/api/public/cron/evaluate-alerts',
    path: '/api/public/cron/evaluate-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pending': typeof PendingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/syncs': typeof AuthenticatedSyncsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/providers/$id': typeof AuthenticatedProvidersIdRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
  '/api/public/cron/sync-billing': typeof ApiPublicCronSyncBillingRoute
  '/api/public/hooks/update-usd-rate': typeof ApiPublicHooksUpdateUsdRateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pending': typeof PendingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/syncs': typeof AuthenticatedSyncsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/providers/$id': typeof AuthenticatedProvidersIdRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
  '/api/public/cron/sync-billing': typeof ApiPublicCronSyncBillingRoute
  '/api/public/hooks/update-usd-rate': typeof ApiPublicHooksUpdateUsdRateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pending': typeof PendingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financial': typeof AuthenticatedFinancialRoute
  '/_authenticated/platforms': typeof AuthenticatedPlatformsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/syncs': typeof AuthenticatedSyncsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/providers/$id': typeof AuthenticatedProvidersIdRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
  '/api/public/cron/sync-billing': typeof ApiPublicCronSyncBillingRoute
  '/api/public/hooks/update-usd-rate': typeof ApiPublicHooksUpdateUsdRateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pending'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/alerts'
    | '/billing'
    | '/clients'
    | '/costs'
    | '/dashboard'
    | '/financial'
    | '/platforms'
    | '/settings'
    | '/syncs'
    | '/users'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/clients/$id'
    | '/providers/$id'
    | '/providers/'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/sync-all'
    | '/api/public/cron/sync-billing'
    | '/api/public/hooks/update-usd-rate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pending'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/alerts'
    | '/billing'
    | '/clients'
    | '/costs'
    | '/dashboard'
    | '/financial'
    | '/platforms'
    | '/settings'
    | '/syncs'
    | '/users'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/clients/$id'
    | '/providers/$id'
    | '/providers'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/sync-all'
    | '/api/public/cron/sync-billing'
    | '/api/public/hooks/update-usd-rate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/pending'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/alerts'
    | '/_authenticated/billing'
    | '/_authenticated/clients'
    | '/_authenticated/costs'
    | '/_authenticated/dashboard'
    | '/_authenticated/financial'
    | '/_authenticated/platforms'
    | '/_authenticated/settings'
    | '/_authenticated/syncs'
    | '/_authenticated/users'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/clients/$id'
    | '/_authenticated/providers/$id'
    | '/_authenticated/providers/'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/sync-all'
    | '/api/public/cron/sync-billing'
    | '/api/public/hooks/update-usd-rate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PendingRoute: typeof PendingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCronEvaluateAlertsRoute: typeof ApiPublicCronEvaluateAlertsRoute
  ApiPublicCronSyncAllRoute: typeof ApiPublicCronSyncAllRoute
  ApiPublicCronSyncBillingRoute: typeof ApiPublicCronSyncBillingRoute
  ApiPublicHooksUpdateUsdRateRoute: typeof ApiPublicHooksUpdateUsdRateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syncs': {
      id: '/_authenticated/syncs'
      path: '/syncs'
      fullPath: '/syncs'
      preLoaderRoute: typeof AuthenticatedSyncsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platforms': {
      id: '/_authenticated/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedPlatformsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial': {
      id: '/_authenticated/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AuthenticatedFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers/$id': {
      id: '/_authenticated/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof AuthenticatedProvidersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/update-usd-rate': {
      id: '/api/public/hooks/update-usd-rate'
      path: '/api/public/hooks/update-usd-rate'
      fullPath: '/api/public/hooks/update-usd-rate'
      preLoaderRoute: typeof ApiPublicHooksUpdateUsdRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-billing': {
      id: '/api/public/cron/sync-billing'
      path: '/api/public/cron/sync-billing'
      fullPath: '/api/public/cron/sync-billing'
      preLoaderRoute: typeof ApiPublicCronSyncBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-all': {
      id: '/api/public/cron/sync-all'
      path: '/api/public/cron/sync-all'
      fullPath: '/api/public/cron/sync-all'
      preLoaderRoute: typeof ApiPublicCronSyncAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/evaluate-alerts': {
      id: '/api/public/cron/evaluate-alerts'
      path: '/api/public/cron/evaluate-alerts'
      fullPath: '/api/public/cron/evaluate-alerts'
      preLoaderRoute: typeof ApiPublicCronEvaluateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialRoute: typeof AuthenticatedFinancialRoute
  AuthenticatedPlatformsRoute: typeof AuthenticatedPlatformsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSyncsRoute: typeof AuthenticatedSyncsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedProvidersIdRoute: typeof AuthenticatedProvidersIdRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialRoute: AuthenticatedFinancialRoute,
  AuthenticatedPlatformsRoute: AuthenticatedPlatformsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSyncsRoute: AuthenticatedSyncsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedProvidersIdRoute: AuthenticatedProvidersIdRoute,
  AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PendingRoute: PendingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCronEvaluateAlertsRoute: ApiPublicCronEvaluateAlertsRoute,
  ApiPublicCronSyncAllRoute: ApiPublicCronSyncAllRoute,
  ApiPublicCronSyncBillingRoute: ApiPublicCronSyncBillingRoute,
  ApiPublicHooksUpdateUsdRateRoute: ApiPublicHooksUpdateUsdRateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
