/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSyncsRouteImport } from './routes/_authenticated/syncs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedPlatformsRouteImport } from './routes/_authenticated/platforms'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as ApiPublicCronSyncAllRouteImport } from './routes/api/public/cron/sync-all'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSyncsRoute = AuthenticatedSyncsRouteImport.update({
  id: '/syncs',
  path: '/syncs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformsRoute = AuthenticatedPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronSyncAllRoute = ApiPublicCronSyncAllRouteImport.update({
  id: '/api/public/cron/sync-all',
  path: '/api/public/cron/sync-all',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/syncs': typeof AuthenticatedSyncsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/syncs': typeof AuthenticatedSyncsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/platforms': typeof AuthenticatedPlatformsRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/syncs': typeof AuthenticatedSyncsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/costs'
    | '/dashboard'
    | '/integrations'
    | '/platforms'
    | '/providers'
    | '/settings'
    | '/syncs'
    | '/api/public/cron/sync-all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/costs'
    | '/dashboard'
    | '/integrations'
    | '/platforms'
    | '/providers'
    | '/settings'
    | '/syncs'
    | '/api/public/cron/sync-all'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/costs'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/platforms'
    | '/_authenticated/providers'
    | '/_authenticated/settings'
    | '/_authenticated/syncs'
    | '/api/public/cron/sync-all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronSyncAllRoute: typeof ApiPublicCronSyncAllRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/syncs': {
      id: '/_authenticated/syncs'
      path: '/syncs'
      fullPath: '/syncs'
      preLoaderRoute: typeof AuthenticatedSyncsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platforms': {
      id: '/_authenticated/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedPlatformsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/sync-all': {
      id: '/api/public/cron/sync-all'
      path: '/api/public/cron/sync-all'
      fullPath: '/api/public/cron/sync-all'
      preLoaderRoute: typeof ApiPublicCronSyncAllRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedPlatformsRoute: typeof AuthenticatedPlatformsRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSyncsRoute: typeof AuthenticatedSyncsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedPlatformsRoute: AuthenticatedPlatformsRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSyncsRoute: AuthenticatedSyncsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronSyncAllRoute: ApiPublicCronSyncAllRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
