/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSyncsRouteImport } from './routes/_authenticated/syncs'
import { Route as AuthenticatedSkusRouteImport } from './routes/_authenticated/skus'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPlatformsRouteImport } from './routes/_authenticated/platforms'
import { Route as AuthenticatedForecastsRouteImport } from './routes/_authenticated/forecasts'
import { Route as AuthenticatedFinancialRouteImport } from './routes/_authenticated/financial'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedConsumptionRouteImport } from './routes/_authenticated/consumption'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as ApiPublicCronSyncBillingRouteImport } from './routes/api/public/cron/sync-billing'
import { Route as ApiPublicCronSyncAllRouteImport } from './routes/api/public/cron/sync-all'
import { Route as ApiPublicCronEvaluateAlertsRouteImport } from './routes/api/public/cron/evaluate-alerts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyncsRoute = AuthenticatedSyncsRouteImport.update({
  id: '/syncs',
  path: '/syncs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkusRoute = AuthenticatedSkusRouteImport.update({
  id: '/skus',
  path: '/skus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformsRoute = AuthenticatedPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForecastsRoute = AuthenticatedForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialRoute = AuthenticatedFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsumptionRoute =
  AuthenticatedConsumptionRouteImport.update({
    id: '/consumption',
    path: '/consumption',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const ApiPublicCronSyncBillingRoute =
  ApiPublicCronSyncBillingRouteImport.update({
    id: '/api/public/cron/sync-billing',
    path: '/api/public/cron/sync-billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncAllRoute = ApiPublicCronSyncAllRouteImport.update({
  id: '/api/public/cron/sync-all',
  path: '/api/public/cron/sync-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronEvaluateAlertsRoute =
  ApiPublicCronEvaluateAlertsRouteImport.update({
    id: '/api/public/cron/evaluate-alerts',
    path: '/api/public/cron/evaluate-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/consumption': typeof AuthenticatedConsumptionRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/forecasts': typeof AuthenticatedForecastsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skus': typeof AuthenticatedSkusRoute
  '/syncs': typeof AuthenticatedSyncsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
  '/api/public/cron/sync-billing': typeof ApiPublicCronSyncBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/consumption': typeof AuthenticatedConsumptionRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/forecasts': typeof AuthenticatedForecastsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skus': typeof AuthenticatedSkusRoute
  '/syncs': typeof AuthenticatedSyncsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
  '/api/public/cron/sync-billing': typeof ApiPublicCronSyncBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/consumption': typeof AuthenticatedConsumptionRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financial': typeof AuthenticatedFinancialRoute
  '/_authenticated/forecasts': typeof AuthenticatedForecastsRoute
  '/_authenticated/platforms': typeof AuthenticatedPlatformsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skus': typeof AuthenticatedSkusRoute
  '/_authenticated/syncs': typeof AuthenticatedSyncsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/sync-all': typeof ApiPublicCronSyncAllRoute
  '/api/public/cron/sync-billing': typeof ApiPublicCronSyncBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/billing'
    | '/budgets'
    | '/clients'
    | '/consumption'
    | '/costs'
    | '/dashboard'
    | '/financial'
    | '/forecasts'
    | '/platforms'
    | '/projects'
    | '/providers'
    | '/reports'
    | '/settings'
    | '/skus'
    | '/syncs'
    | '/team'
    | '/clients/$id'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/sync-all'
    | '/api/public/cron/sync-billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/billing'
    | '/budgets'
    | '/clients'
    | '/consumption'
    | '/costs'
    | '/dashboard'
    | '/financial'
    | '/forecasts'
    | '/platforms'
    | '/projects'
    | '/providers'
    | '/reports'
    | '/settings'
    | '/skus'
    | '/syncs'
    | '/team'
    | '/clients/$id'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/sync-all'
    | '/api/public/cron/sync-billing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/billing'
    | '/_authenticated/budgets'
    | '/_authenticated/clients'
    | '/_authenticated/consumption'
    | '/_authenticated/costs'
    | '/_authenticated/dashboard'
    | '/_authenticated/financial'
    | '/_authenticated/forecasts'
    | '/_authenticated/platforms'
    | '/_authenticated/projects'
    | '/_authenticated/providers'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/skus'
    | '/_authenticated/syncs'
    | '/_authenticated/team'
    | '/_authenticated/clients/$id'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/sync-all'
    | '/api/public/cron/sync-billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronEvaluateAlertsRoute: typeof ApiPublicCronEvaluateAlertsRoute
  ApiPublicCronSyncAllRoute: typeof ApiPublicCronSyncAllRoute
  ApiPublicCronSyncBillingRoute: typeof ApiPublicCronSyncBillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syncs': {
      id: '/_authenticated/syncs'
      path: '/syncs'
      fullPath: '/syncs'
      preLoaderRoute: typeof AuthenticatedSyncsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skus': {
      id: '/_authenticated/skus'
      path: '/skus'
      fullPath: '/skus'
      preLoaderRoute: typeof AuthenticatedSkusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platforms': {
      id: '/_authenticated/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedPlatformsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecasts': {
      id: '/_authenticated/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof AuthenticatedForecastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial': {
      id: '/_authenticated/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AuthenticatedFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consumption': {
      id: '/_authenticated/consumption'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof AuthenticatedConsumptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/cron/sync-billing': {
      id: '/api/public/cron/sync-billing'
      path: '/api/public/cron/sync-billing'
      fullPath: '/api/public/cron/sync-billing'
      preLoaderRoute: typeof ApiPublicCronSyncBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-all': {
      id: '/api/public/cron/sync-all'
      path: '/api/public/cron/sync-all'
      fullPath: '/api/public/cron/sync-all'
      preLoaderRoute: typeof ApiPublicCronSyncAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/evaluate-alerts': {
      id: '/api/public/cron/evaluate-alerts'
      path: '/api/public/cron/evaluate-alerts'
      fullPath: '/api/public/cron/evaluate-alerts'
      preLoaderRoute: typeof ApiPublicCronEvaluateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedConsumptionRoute: typeof AuthenticatedConsumptionRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialRoute: typeof AuthenticatedFinancialRoute
  AuthenticatedForecastsRoute: typeof AuthenticatedForecastsRoute
  AuthenticatedPlatformsRoute: typeof AuthenticatedPlatformsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkusRoute: typeof AuthenticatedSkusRoute
  AuthenticatedSyncsRoute: typeof AuthenticatedSyncsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedConsumptionRoute: AuthenticatedConsumptionRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialRoute: AuthenticatedFinancialRoute,
  AuthenticatedForecastsRoute: AuthenticatedForecastsRoute,
  AuthenticatedPlatformsRoute: AuthenticatedPlatformsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkusRoute: AuthenticatedSkusRoute,
  AuthenticatedSyncsRoute: AuthenticatedSyncsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronEvaluateAlertsRoute: ApiPublicCronEvaluateAlertsRoute,
  ApiPublicCronSyncAllRoute: ApiPublicCronSyncAllRoute,
  ApiPublicCronSyncBillingRoute: ApiPublicCronSyncBillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
